services:
  # App Service
  app:
    build:
      context: ../ # Use an image built from the specified dockerfile in the current directory.
      dockerfile: build/Dockerfile
    restart: unless-stopped
    env_file:
      - ../config/wallex.conf